### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/edgytech/swingfast/Application

### ISSUE THREAD

**Issue by atwskris** [agirbal/umongo#50] opened 2011-11-29 08:06 UTC
Exception in thread "main" java.lang.NoClassDefFoundError: com/edgytech/swingfast/Application
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Caused by: java.lang.ClassNotFoundException: com.edgytech.swingfast.Application
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 12 more
Could not find the main class: org.mongo.jmongob.JMongoBrowser. Program will exit.

Hope this help, please let me know if you need more details, architecture, environment etc...
K

**Comment by agirbal** [comment] 2011-11-29 08:13
how are you starting the app?
Make sure you follow the steps at https://github.com/agirbal/JMongoBrowser/wiki
If it doesnt work, let me know your OS.
thx

**Comment by atwskris** [comment] 2011-11-29 18:33
I have tired starting the app by command line and also by clicking on it
directly.
The execute permissions are set.
I am using Ubuntu 11.10 64 bit and sun-java6-jdk/jre/bin/plugin are all
also installed.

K

On Tue, Nov 29, 2011 at 12:13 AM, Antoine Girbal <
reply@reply.github.com

**Comment by agirbal** [comment] 2011-11-29 19:10
ok can you give me:
- the exact command line you are using to start it?
- result of "sudo update-java-alternatives -l"
- result of "ls -l ./JMongoBrowser-linux-all_1-1-1/lib/"

**Comment by atwskris** [comment] 2011-11-29 19:17
I  will have to get the rest of you when I get back home tonight.
However the command I used to start is:  ./launchJMongoBrowser.sh

K

On Tue, Nov 29, 2011 at 11:10 AM, Antoine Girbal <
reply@reply.github.com

**Comment by hyperrjas** [comment] 2011-11-30 23:34
I use rails 3.1 with MongoDb and Mongoid in ubuntu maverick 10.10.

This is my report in console when I run ./launchJMongoBrowser.sh or double click in sh file:

Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
    at com.edgytech.swingfast.ButtonBase.xmlPostLoadComponentCallback(ButtonBase.java:344)
    at com.edgytech.swingfast.XmlComponentUnit.xmlPostLoadCallback(XmlComponentUnit.java:423)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:903)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
    at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
    at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
    at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
    at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
    at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
    at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
    at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
    at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
    at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
    at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
    at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
    at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:779)
    at com.edgytech.swingfast.XmlUnit.xmlCreateAndAddChild(XmlUnit.java:668)
    at com.edgytech.swingfast.XmlUnit.addAllChildren(XmlUnit.java:1270)
    at com.edgytech.swingfast.XmlUnit.structure(XmlUnit.java:1196)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:870)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:804)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:953)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:963)
    at com.edgytech.swingfast.XmlUnit.xmlLoad(XmlUnit.java:959)
    at org.mongo.jmongob.JMongoBrowser.load(JMongoBrowser.java:85)
    at org.mongo.jmongob.JMongoBrowser.initialize(JMongoBrowser.java:111)
    at com.edgytech.swingfast.Application$1.run(Application.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:647)
    at java.awt.EventQueue.access$000(EventQueue.java:96)
    at java.awt.EventQueue$1.run(EventQueue.java:608)
    at java.awt.EventQueue$1.run(EventQueue.java:606)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:105)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:617)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
Caused by: java.awt.HeadlessException
    at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:231)
    at com.edgytech.swingfast.ButtonBase$KeyModifier.<clinit>(ButtonBase.java:236)
    ... 54 more

This is report when I run sudo update-java-alternatives -l:

java-6-openjdk 1061 /usr/lib/jvm/java-6-openjdk

Thanks!

**Comment by agirbal** [comment] 2011-12-01 00:23
Note that this app is a desktop GUI, to be run on your client not the server.
It expects a valid display and keyboard, and it seems here java does not detect any.

**Comment by atwskris** [comment] 2011-12-01 00:37
I am aware this is a desktop GUI.

Ubuntu 11.10
KDE 4.6
Kernel 3.0.13

Hope this helps.
Please let me know if you require any additional information.

On Wed, Nov 30, 2011 at 4:23 PM, Antoine Girbal
reply@reply.github.com
wrote:

**Comment by hyperrjas** [comment] 2011-12-01 00:43
Thank you agirbal, Im not runing since server. Im runing the .sh since desktop like admin from my pc. I have ubuntu maverick desktop. I have not ubuntu server.

I need a new version Java? My current version is java-6-openjdk.

I have ubuntu 10.10 maverick in vmware. If you help me for fix this error any help would be appreciated.

Thank you

**Comment by agirbal** [comment] 2011-12-01 03:19
@atwskris:

Can you run:
$ sudo update-java-alternatives -l

I am suspecting that your default java is not openjdk 6 but something else like gnu.

Also what is your default shell?
$ ll /bin/sh
lrwxrwxrwx 1 root root 4 2011-05-09 10:27 /bin/sh -> bash*

The actual command line that you can execute from the JMongoBrowser folder is:
java -classpath './lib/*.jar' -Xms64M -Xmx512M -Djava.util.logging.config.file=./logging.properties -jar JMongoBrowser.jar

If that still gives you an error, try:
java -classpath './lib/mongo.jar:./lib/SwingFast.jar' -Xms64M -Xmx512M -Djava.util.logging.config.file=./logging.properties -jar JMongoBrowser.jar

**Comment by agirbal** [comment] 2011-12-01 03:20
@hyperrjas: your error is different, I am moving it to issue #51

**Comment by atwskris** [comment] 2011-12-01 04:04
On 11-11-30 07:19 PM, Antoine Girbal wrote:

> @atwskris:
> 
> Can you run:
> $ sudo update-java-alternatives -l
> 
> I am suspecting that your default java is not openjdk 6 but something else like gnu.
> 
> Also what is your default shell?
> $ ll /bin/sh
> lrwxrwxrwx 1 root root 4 2011-05-09 10:27 /bin/sh ->  bash*
> 
> The actual command line that you can execute from the JMongoBrowser folder is:
> java -classpath './lib/*.jar' -Xms64M -Xmx512M -Djava.util.logging.config.file=./logging.properties -jar JMongoBrowser.jar
> 
> If that still gives you an error, try:
> java -classpath './lib/mongo.jar:./lib/SwingFast.jar' -Xms64M -Xmx512M -Djava.util.logging.config.file=./logging.properties -jar JMongoBrowser.jar
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/agirbal/JMongoBrowser/issues/50#issuecomment-2970343
> 
> Hi Antoine,

$ sudo update-java-alternatives -l

java-6-sun 63 /usr/lib/jvm/java-6-sun

$ ll /bin/sh

lrwxrwxrwx 1 root root 4 2011-05-03 08:04 /bin/sh -> dash*

java -classpath './lib/*.jar' -Xms64M -Xmx512M -Djava.util.logging.config.file=./logging.properties -jar JMongoBrowser.jar

Exception in thread "main" java.lang.NoClassDefFoundError: 
com/edgytech/swingfast/Application
         at java.lang.ClassLoader.defineClass1(Native Method)
         at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
         at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
         at 
java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
         at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
         at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
         at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
         at java.security.AccessController.doPrivileged(Native Method)
         at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Caused by: java.lang.ClassNotFoundException: 
com.edgytech.swingfast.Application
         at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
         at java.security.AccessController.doPrivileged(Native Method)
         at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
         ... 12 more
Could not find the main class: org.mongo.jmongob.JMongoBrowser. Program 
will exit.

java -classpath './lib/mongo.jar:./lib/SwingFast.jar' -Xms64M -Xmx512M -Djava.util.logging.config.file=./logging.properties -jar JMongoBrowser.jar

Exception in thread "main" java.lang.NoClassDefFoundError: 
com/edgytech/swingfast/Application
         at java.lang.ClassLoader.defineClass1(Native Method)
         at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
         at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
         at 
java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
         at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
         at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
         at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
         at java.security.AccessController.doPrivileged(Native Method)
         at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Caused by: java.lang.ClassNotFoundException: 
com.edgytech.swingfast.Application
         at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
         at java.security.AccessController.doPrivileged(Native Method)
         at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
         ... 12 more
Could not find the main class: org.mongo.jmongob.JMongoBrowser. Program 
will exit.

**Comment by agirbal** [comment] 2011-12-01 17:53
that's really odd I tried with the same jre and no issue.
Could you install and use openjdk instead?
$ sudo apt-get install openjdk-6-jdk

Then you should see it in the list of java alternatives.
Then can you go to the browser folder (version 1.1.1) and type:

$ pwd
$ ls -l
$ ls -l lib
$ /usr/lib/jvm/java-6-openjdk/bin/java -classpath './lib/*.jar' -Xms64M -Xmx512M -Djava.util.logging.config.file=./logging.properties -jar JMongoBrowser.jar

**Comment by agirbal** [comment] 2011-12-02 20:20
any luck?

**Comment by atwskris** [comment] 2011-12-02 21:23
Haven't tried yet will hope to tonight and will let you know.
Thanks for checking in.

On Fri, Dec 2, 2011 at 12:20 PM, Antoine Girbal <
reply@reply.github.com

**Comment by olagache** [comment] 2012-08-21 16:41
Hi, 
I had the same problem, and finally I change the launcher script like this: https://gist.github.com/3416805
Hope this can help you.

**Comment by agirbal** [comment] 2013-10-07 01:54
Do you still have the issue with UMongo?
The gist just checks for Java home, but you shouldnt have an issue if java is set up properly.

**Closed as completed by agirbal** 2013-10-07 01:54 UTC
