### ISSUE TITLE
umongo import not using utf-8

### ISSUE THREAD

**Issue by DieMoe** [agirbal/umongo#235] opened 2014-06-22 12:56 UTC
Hi, I have a problem using the umongo Collection Import and Export. Umongo seemed not to keep UTF-8 encoding tested on german Umlaute.

I buildt 2 import files
console.json:
   {
       "Type": "console",
       "Name": "Dieter Möller"
   }
and umongo.json:
   {
       "Type": "umongo",
       "Name": "Dieter Möller"
   }

First I was using command line inside a console: 
   mongoimport -d myDB -c Profil --jsonArray > console.json

And then I was using the import file umongo.json within umongo. 

Umungo shows the whole collection as 
   {
     "_id": {"$oid": "53a6c9e46b8f4a3362904ea8"},
     "Type": "console",
     "Name": "Dieter Möller"
   }
   {
       "_id": {"$oid": "53a6ca2daa4f388f478fb17d"},
     "Type": "umungo",
     "Name": "Dieter MÃ¶ller"
   }
It seemed that Umongo ist doing the import in a different way than MongoDB is doing it.

Similiar problem I found for Export. I was using the export inside the console using
   mongoexport -d myDB -c Profil --jsonArray > console-export.json
and got the following content:
   [{ "_id" : { "$oid" : "53a6c9e46b8f4a3362904ea8" }, 
       "Type" : "console", 
       "Name" :    "Dieter Möller" },
    { "_id" : { "$oid" : "53a6ca2daa4f388f478fb17d" }, 
       "Type" : "umungo", 
       "Name" : "Dieter MÃ¶ller" 
    }]
Using the umongo export I got a file with a different content:
   [{ "_id" : { "$oid" : "53a6c9e46b8f4a3362904ea8"} , 
      "Type" : "console" , 
      "Name" : "Dieter M�ller"},
   { "_id" : { "$oid" : "53a6ca2daa4f388f478fb17d"} , 
      "Type" : "umungo" , 
      "Name" : "Dieter Möller"
   }]

Hope you can help.
Regards Dieter

**Comment by SONEINT** [comment] 2014-07-07 21:25
I have a similar problem with Umongo export facilities. Are you using a WINDOWS OS machine ?
Look at "Wrong export collection format in multi-languages (with arabic) #221" dealing probably with UTF-8 Endoding ( ) https://github.com/agirbal/umongo/issues/221 

Cyrille.

**Comment by agirbal** [comment] 2014-07-22 16:20
ok again like for https://github.com/agirbal/umongo/issues/238 I can't reproduce with umongo 1.6.2. Which version are you using? which OS? thanks

**Comment by agirbal** [comment] 2014-07-22 16:27
Ok I tried with umongo 1.4.3 and it was messed up. Looks like either a bug in umongo or java driver that was fixed. Can you confirm?

**Comment by agirbal** [comment] 2014-07-24 09:07
Closing unless you say the problem is still there, thx!

**Closed as completed by agirbal** 2014-07-24 09:07 UTC

**Comment by SONEINT** [comment] 2014-07-24 10:40
Hi,

Thanks for your work. I hope it was a Umongo version update problem. 

I'm sorry but I'm not at home for a few weeks, not able to test it before 2 weeks I think. I will check ASAP the Umongo version.

Kind regards,

Cyrille.
